config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :posts

  authenticated :user do
    root :to => 'posts#index'
  end
  root :to => "posts#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  embedded_in :post
  field :name, :type => String
  field :body, :type => String
end

app/models/part.rb
class Part
  include Mongoid::Document
  embedded_in :post
  field :body, :type => String
end

app/models/post.rb
class Post
  include Mongoid::Document
  embeds_many :comments
  embeds_many :parts
  field :name, :type => String
  field :patrs, :type => Array
  field :comments, :type => Array
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index :email, :unique => true
  field :name
  validates_presence_of :name
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create    
    @post = Post.find(params[:id])
    comment = @post.comments.new    
    comment.update_attributes(:name => params[:name], :body => params[:body])
    redirect_to posts_path
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    #@posts = Post.paginate(:page => 1, :per_page => 1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    1.times {@post.parts.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    1.times {@post.parts.build}
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  -if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Name
    %th Body
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.name
      %td= comment.body
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @comment.name
%p
  %b Body:
  = @comment.body

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Blog", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Blog"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/posts/_form.html.haml
=javascript_include_tag 'jquery.table.addrow.js'
.bodyContainer
  %h1 Create your blog
  
  #registrationExplanation
    This blog is developed and designed by Pravin Kumar
  
  
    -if @post.errors.any?
      %form.standardForm
        .formTopErrorText
          %span.formTopErrorHeader> Oops!
          #error_head_text We discovered an error. Please see below for more information.          

    = form_for @post, :html =>{ :class => 'standardForm'} do |f|
      
      .formBox
        .formSection Blog Tile
        = f.label :name, "Title" 
        = f.text_field :name

      .formBox
        .formSection Blog parts

        %table{ :class => 'atable'}
          -@post.parts.each_with_index do |part,index|
            = f.fields_for "part_attributes[]", part do |part_fields|
        
              %tr
                %td{:class => 'table_hr'}
                  = part_fields.label :body
                  = part_fields.text_area :body                                                     

                  %span.alternativeRow Add parts
              
              %tr
                %td{:class => 'table_hr'}
                  = part_fields.label :body
                  = part_fields.text_area :body
                                  
                  %span.delRow Remove part

      = f.submit 'continue'  

:javascript
  $("document").ready(function(){
  	$(".alternativeRow").btnAddRow({oddRowCSS:"oddRow",evenRowCSS:"evenRow"});
  	$(".delRow").btnDelRow();
  });

app/views/posts/edit.html.haml
= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      Post Title  
      %td= post.name        
      %table
      %h3 Post:
      - post.part_attributes.each do |part|          
        - part.each do |aPart|
          %tr
            %td
              = aPart[1]
              %br
      %h3 Comments:
      - post.comments.each do |comment|          
        %h5 Commnet By:
        = comment.name
        %h5 Commnet:
        = comment.body

      
      -#= debug(post.comments)       

      = form_tag comments_path(:id =>post.id), :method => 'post', :class=>'form-search' do
        %label Name
        = text_field_tag :name
        %label Comment
        = text_area_tag :body
        = submit_tag :comment, :name => 'Post', :class => "btn btn-primary btn-small"        
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete
      %hr
%br
-#= will_paginate @posts
%hr
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @post.name
  %table
    %h3 Post:
    - @post.part_attributes.each do |part|          
      - part.each do |aPart|
        %tr
          %td
            = aPart[1]
            %br
    %h3 Comments:
    - @post.comments.each do |comment|          
      %h5 Commnet By:
      = comment.name
      %h5 Commnet:
      = comment.body

      
    -#= debug(post.comments)

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/index.html.haml
%h2 Users
- @users.each do |user|
  %br/
  #{link_to user.email, user} signed up #{user.created_at.to_date}

= will_paginate

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}